### ISSUE TITLE
As a News Manager I want to be able to create a new blog post so that I can provide the public with information about the camp

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#1]
Acceptance

Content type labeled Blog Post
- A Title Field
- A WYSIWYG Field labeled Body
- A Term reference field labeled Tags that references the Blog Tags vocabulary and accepts multiple tags

Path alias should be set up to generate urls /blog/[date:year]/[date:month]/[node:title]

**Comment by jnettik** [comment]
Content type for blog posts is finished. Could use another set of eyes maybe.

**Comment by nswitzer** [comment]
Hey @jnettik - I added a couple test posts to the site. Looks like we still need CKeditor enabled for the body field and the tag reference field added.

**Comment by nswitzer** [comment]
@jnettik - Whoops, looks like there was some config that still need to be imported. I imported all of that on the dev site and the tag reference field showed up, but we do still need CKeditor enabled.

**Comment by nswitzer** [comment]
Looks good. Closing
