### ISSUE TITLE
Theme sponsorship opportunities grid

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#11]
Design for reference: https://projects.invisionapp.com/share/XJE4W9E86#/screens/272188623

**Comment by nswitzer** [comment]
Hey @jnettik - Are you open to working on this one, since you seem to have a pretty clear vision of where to take this after building out the terms?

**Comment by jnettik** [comment]
@nswitzer this is ready to check out. If you set the spots available field to -1 it will set it as Unlimited on the front end.

**Comment by nswitzer** [comment]
This looks great. Thanks @jnettik!
