### ISSUE TITLE
Build testimonials library.

### ISSUE THREAD

**Issue by jnettik** [DrupalCampColorado/dcco2018#13]
This is for the testimonials that are used at the bottom of pages. I'm thinking it might make sense to create a custom Testimonial entity for these that would serve as a repository of testimonials. This could then be something we place through entity reference fields on a Paragraph or Custom block type or something. Partly I just want to test out custom content entities, but I do think this would make them more portable. Thoughts?

**Comment by nswitzer** [comment]
Yeah, I like that idea. I updated the build spec to include a 'testimonial' bundle in a 'promotions' entity type that we can use if we have other one off bundles like this come up. I've accounted for a 'reference - block' paragraph that we can use to reference a views block of all testimonials, with the sort set to random - you think that will work?

**Comment by tmlangley** [comment]
I'm curious what the advantages of a custom entity are here? I'm all for trying new things but I do feel like we might be overcomplicating things by creating a custom entity over just a content type. Even with the console generator, custom entities types tend to add a decent amount of work both in creation and maintenance.

**Comment by nswitzer** [comment]
Ah, thanks for the insight there @tandroid1. A content type still gives us the flexibility of creating a views block that we can set up to display random testimonials, though we'll still need to figure out the caching issues associated with that. Updating the build spec once more, but definitely open to continuing the conversation.

**Comment by jnettik** [comment]
Personally I think of nodes as being used for content that warrants a full page; blog post, events, profiles, etc. Testimonials are often added as part of a page, but you'd never go to `site.com/testimonials/tanners-awesome-comment`. Assignment to a menu, application of metadata, much of the functionality associated with nodes feels like cruft for a single testimonial. I think of them similarly to most media items, a piece of a page but rarely the full page itself.

**Comment by nswitzer** [comment]
Yep, that makes sense. Let's go with custom entities and I'll leave this assigned to you @jnettik.

**Comment by jnettik** [comment]
Sounds good. If I start hitting hurdles slowing me down too much I'll bail for something else.

**Comment by nswitzer** [comment]
hey @jnettik - we were able to move the testimonial component from the landing page in a couple minutes and it's totally usable, with themeing and everything. If you still want to build this as a custom entity, that's fine, but I wanted to give you a heads up that we can prioritize other site building items for phase 1 since we only have 1 week left before launch.

**Comment by nswitzer** [comment]
@jnettik and @tandroid1 - I'm going to close this out since we're going with the component solution for now.
