### ISSUE TITLE
Theme sponsor detail pages

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#15]
Please theme these according to the news detail design, except there won't be any blocks placed in the sidebar.

https://projects.invisionapp.com/share/XJE4W9E86#/screens/272188621

**Comment by eric-schmidt** [comment]
@nswitzer This page is now adopting the same styles as the blog detail. I went ahead and also moved the logo display to the sidebar, as it seemed to balance the page a bit more. This can easily be moved into the content on the left if need be.

**Comment by nswitzer** [comment]
This looks great. Thanks @eric-schmidt!
