### ISSUE TITLE
Build media entities and configure browser

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#17]
Hey @tandroid1 - let's talk some more about what we can pull from Paragon here.

**Comment by tmlangley** [comment]
I'm going to try and see if I can export this stuff with features. I didn't really think about it but the component building is a bit held up without this stuff.

**Comment by nswitzer** [comment]
Hey @tandroid1 - I'm going to go ahead and close this task since we've decided to move forward without media given our time constraints. We can reopen if we choose to revisit.
