### ISSUE TITLE
Theme Banner - Featured Header component

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#19]

**Comment by nswitzer** [comment]
@tandroid1  - @bjornbreck is going to take this one

**Comment by nswitzer** [comment]
Hey @bjornbreck - This is looking really good. I'm seeing to small issues in IE11 I'm hoping you can address:
1. The size of the logo.
2. Alignment of the sign up form.

Screenshot below

![image](https://user-images.githubusercontent.com/1634837/36077218-0b642b4c-0f25-11e8-9559-5a44ec3e6e3b.png)

**Comment by bjornbreck** [comment]
Hey @nswitzer, I updated the logo size for IE11 and aligned the button on the left of the form as well.

**Comment by nswitzer** [comment]
Looks good @bjornbreck! Thanks for taking care of this.
