### ISSUE TITLE
As an anonymous user I want to go to be able to see all blogs of a certain type so that I may be able to reference that type directly. 

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#2]
Acceptance

A path alias on the Blog Tags vocabulary to /blog/[term:name]

**Comment by jnettik** [comment]
There's a blog view with three displays. The page display is disabled and will be used for the camp distro. The mirrored block can get pulled in via paragaraphs and the landing page content type. And there's a recent updates block that we can use for the homepage (also via paragraphs).
