### ISSUE TITLE
Theme Banner - Simple component

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#20]

**Comment by nswitzer** [comment]
Hey @bjornbreck - This is looking good. Two things I'm seeing that need to be updated:
1. The heading field should render as an `<h1>`
2. The heading field should be a different font. I know the fonts aren't updated in avocode, so let me know if need a hand tracking this down. Reference: https://projects.invisionapp.com/share/XJE4W9E86#/screens/272188622

**Comment by bjornbreck** [comment]
Hey @nswitzer, I updated the template to print the h1 for the header and switched the font to arvo.

**Comment by nswitzer** [comment]
Great, looks good to me.
