### ISSUE TITLE
Theme login and password reset forms

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#26]
This doesn't need to be anything fancy, but we should apply the global layout, form and button styles to these pages.

https://2018.drupalcampcolorado.org/user/login
https://2018.drupalcampcolorado.org/user/password

**Comment by eric-schmidt** [comment]
@nswitzer This is all set on 2-x!

**Comment by nswitzer** [comment]
Looks great, thanks @eric-schmidt!
