### ISSUE TITLE
Placeholder headshot for profiles.

### ISSUE THREAD

**Issue by jnettik** [DrupalCampColorado/dcco2018#27]
We need a default image to use for the customer profile type's headshot image field.

**Comment by jnettik** [comment]
@nswitzer 

We sorta have two options here:

1. Use the same placeholder we've been using for a couple years now. It's a great graphic, however it doesn't quite match the current design. http://2017.drupalcampcolorado.org/sites/default/files/styles/medium/public/default_images/default-avatar_09886.png?itok=9XeI8IK6
2. We come up with a new one, which is a bit outside my wheelhouse. But if any of the designers who've helped us so far have ideas it might fit better into the design.

Thoughts?

**Comment by nswitzer** [comment]
@jnettik Based on our conversation in Slack, please go ahead and use the Yeti druplicon desaturated.

**Comment by jnettik** [comment]
This is done.

**Comment by nswitzer** [comment]
Looks great. Thanks @jnettik
