### ISSUE TITLE
Theme cart page

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#31]

**Comment by jnettik** [comment]
I'm not sure if this is needed. Working through the checkout process and it feels unnecessary to me. Currently you have to add an item to your cart, click the cart dropdown, go to cart, go to checkout. I'm testing out a patch to commerce that will make it so when we add a registration to the cart, it drops you right into checkout. This seems like a more streamlined checkout process for users who are generally only ever going to buy one thing from us.

**Comment by nswitzer** [comment]
@jnettik Nice! That sounds good to me. I created #37 and assigned to you to track progress on that. I'll mark this as hold for now.

**Comment by nswitzer** [comment]
No longer needed. Closing.
