### ISSUE TITLE
Theme order confirmation

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#33]
We need to theme this page and update the content to display an order summary.

**Comment by jnettik** [comment]
I got a template started, and added the current user if logged in. I think it'll be helpful to prompt them to fill out their profiles on this page with a link taking them to their edit page.

**Comment by nswitzer** [comment]
Nice, thanks @jnettik - could you also add a view to display an order summary, similar to what displays in the orders tab of the user profile?

**Comment by nswitzer** [comment]
Created #40 to track adding the summary view. Leaving this open until that view has been added in case it needs themeing.

**Comment by nswitzer** [comment]
All good here. The summary view looks good. Closing.
