### ISSUE TITLE
Add fields for user profile.

### ISSUE THREAD

**Issue by jnettik** [DrupalCampColorado/dcco2018#34]
Added fields for:

- Name
- Headshot
- Company
- Company URL
- Bio
- Social Media Links
- Job Title

We'll need a default image for the headshot, which I listed in another ticket. We could pull the one from past camps, but it might not match our new design. The social links field is a multi value field. I figure instead of locking people down to a handful of services, they can provide the link and title for whatever appeals to them.

**Comment by jnettik** [comment]
Links are all done. The URL doesn't need to be displayed. The company name will be wrapped in it if a user provides a value. All that should be needed is theming.

**Comment by nswitzer** [comment]
Hey @jnettik - This is looking good. One small thing, when I add data to all the fields, I'm getting a PHP Notice: Only variables should be passed by reference in themekit_preprocess_field() (line 108 of themes/custom/themekit/themekit.theme).

**Comment by jnettik** [comment]
This has been fixed.

**Comment by nswitzer** [comment]
Thanks @jnettik - looks like we're all good here.
