### ISSUE TITLE
Theme registrant profile

### ISSUE THREAD

**Issue by jnettik** [DrupalCampColorado/dcco2018#36]

**Comment by nswitzer** [comment]
Hey @jnettik - I wanted to add here that I disabled the ability for the authenticated user role to use the admin theme because it creates kind of a weird edit profile experience. The styles that the edit form inherit look pretty good, I think we'll just need to clean it up a bit.

**Comment by jnettik** [comment]
Makes sense to me.

**Comment by nswitzer** [comment]
@tandroid1 - as part of this one, could you also do a little cleanup on the profile edit form for authenticated users who don't have access to the admin theme? It mostly works fine, but the name fieldset could use some borders and the labels moved above the fields and I'd like to update the description for the organization website field so it's a little more friendly.

**Comment by nswitzer** [comment]
Looks great. Thanks @tandroid1
