### ISSUE TITLE
Theme user account menu

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#38]
I've added the user account menu to the header, please theme it to display above the main site nav.

**Comment by eric-schmidt** [comment]
@nswitzer This is all set on 2-x. For the sake of simplicity, I'm just cloning the utility menu and appending to the off canvas menu for mobile. Let me know if you think this needs any more work

**Comment by nswitzer** [comment]
@eric-schmidt - Looks good to me. Thanks!
