### ISSUE TITLE
Theme news list display

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#4]
Theme list of news posts that is output by Views. This will require templating the news teaser view mode that is used to display the news posts in the views listings. Appears on the homepage and news overview comps, references below.

Homepage: https://projects.invisionapp.com/share/XJE4W9E86#/screens/273515223
News overview: https://projects.invisionapp.com/share/XJE4W9E86#/screens/272188622

**Comment by eric-schmidt** [comment]
@nswitzer This should be all set on both the homepage and news overview pages.

**Comment by nswitzer** [comment]
Looks good, thanks @eric-schmidt!
