### ISSUE TITLE
Add order summary to order confirmation

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#40]
Above the other content on the order confirmation page, please add an order summary that include the order number, product, quantity and price.

**Comment by jnettik** [comment]
This has been done. I think some of the final verbiage could be improved on, but this basically pulls in the order summary table view into that template.

**Comment by nswitzer** [comment]
Awesome, thanks @jnettik. This looks way better. I updated the copy too, so I think we're all set here.
