### ISSUE TITLE
Theme register link as orange button

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#42]
Please theme the register link in the main nav as an orange button

**Comment by eric-schmidt** [comment]
@nswitzer This is all set on 2-x. I also noticed that menu spacing gets a little borked as you scale down to mobile--I'll go ahead and address this when I implement the fix for https://github.com/DrupalCampColorado/dcco2018/issues/38

**Comment by nswitzer** [comment]
@eric-schmidt - No worries, that's good with me. Could you also theme the register link text color to be orange in the mobile menu?

**Comment by eric-schmidt** [comment]
@nswitzer All set--I went ahead and just made it a button on mobile as well, as I think looks better and is more consistent.

**Comment by nswitzer** [comment]
Looks great. Thanks @eric-schmidt.
