### ISSUE TITLE
Placeholder content on user profile page

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#43]
When a user has registered and doesn't have any information added to their profile, there is nothing on the page. Could we add some content on that page to display until they complete their profile? I'm thinking something along the lines of:
"Please tell us a little about yourself - update your profile now!"

**Comment by jnettik** [comment]
That makes sense for when a user is viewing their own empty profile, however what should be there if you're viewing someone else's profile that's empty. There will at least be the default image, (see #27). The 2017 site handles this a little awkward. There's a giant heading that says "Say hello to user {{ username }}", and then below that there's their real name. I'm wondering we use that same "Say hello" text, but use their username by default and their full name if provided.

For reference: http://2017.drupalcampcolorado.org/user-personal-information/howard.html

**Comment by jnettik** [comment]
@nswitzer This piece is done. If a user's profile is empty and they're logged in, they'll see that message. It can be tweaked in the Twig template if necessary. I've also added the user name title block. If the profile is empty, it defaults to the username. If they put in a real name, the block uses that instead. It's hard to see right now, there's some styling in place that visually hides the page title block content. You can confirm the content is there in the inspector. I'm not sure why we'd be hiding `.page-title`, so I didn't want to mess with it and break something elsewhere.

I figure the user name could look like we have the blog titles elsewhere in the site.

**Comment by nswitzer** [comment]
Nice, this works for me. Thanks @jnettik.
