### ISSUE TITLE
Configure Stripe as payment gateway

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#44]
I have access to the DCCO account, now I need to configure this as the main payment gateway for the site.

**Comment by nswitzer** [comment]
Stripe is configured as the main payment method and is in test mode. Test credit card data can be found here.

**Comment by jnettik** [comment]
Pretty sure this is the link: https://stripe.com/docs/testing#cards

**Comment by jnettik** [comment]
I just ran some tests. This looks really good.

**Comment by tmlangley** [comment]
I just pushed up some styling for this so it's consistent with the rest of the form.

**Comment by nswitzer** [comment]
Awesome, thanks for testing guys. I was able to confirm that your test payments went through to Stripe. I think we're all good here!
