### ISSUE TITLE
Theme news detail

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#5]
Apply themeing specific to the news detail page.

Reference: https://projects.invisionapp.com/share/XJE4W9E86#/screens/272188621

**Comment by eric-schmidt** [comment]
@nswitzer All set and ready for review!

**Comment by eric-schmidt** [comment]
@nswitzer I also added the ability to apply headings in the body. H2's are properly styled.

**Comment by nswitzer** [comment]
Looks great @eric-schmidt! Thanks.
