### ISSUE TITLE
Create session content type.

### ISSUE THREAD

**Issue by jnettik** [DrupalCampColorado/dcco2018#50]
Create a content type called Session with fields for:

- Title
- Speaker(s) : Entity reference to user accounts
- Track : Entity reference to a new Session Track vocabulary
- Description

I think that's the minimum we'd need for now. Questions I have are:

1. Do we need a field/taxonomy for session level, e.g. Beginner, Intermediate, Advanced?
2. Do we need a field for session duration, e.g. 30 min, 45 min. If so, I'd suggest making this a hardcoded text list in favor of a taxonomy as we might need to do some schedule logic around this in the future.
3. Are the parties and trainings going to be the same content type or their own? What about the keynote? Do we need a field to distinguish "Session Types"?

Other fields we'll need at some point, but not necessarily now are:

- Time 
- Room (Taxonomy reference)
- Session Video (for recordings)

Have I missed anything for this?

**Comment by nswitzer** [comment]
Hey @jnettik - This looks good to me. Here's what I'm thinking for your questions:
1. Yes, let's do what you mentioned: beginner, intermediate and advanced.
2. Yeah, to stay consistent with what we did last year and what Drupalcon is doing, let's do 30 min or 60 min. I'm good with making this a hardcoded text list.
3. I think we can make the parties and trainings the same content type - I don't see a reason to distinguish them right now, but let me know if there's something I'm missing there.

This also made me realize we'll need a field for track. Here's what I'm thinking for the session tracks: Site Building, Frontend, Backend, Business, Project Management, Design and UX, Content and Editorial. It would probably also make sense to add party, training and summit to that list.

Let me know what you think!

**Comment by jnettik** [comment]
This is ready for review on develop.

**Comment by nswitzer** [comment]
Nice, thanks @jnettik. This looks good.
