### ISSUE TITLE
Theme session submission form

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#56]
https://full2018.drupalcampcolorado.org.develop.us2.compact.amazee.io/node/add/session

The session submission form mostly needs some layout styles applied. Please theme the "add another item" (can we change that text to "add another speaker"?) button as the gray button style we use elsewhere on the site. The save button should be themed as the orange CTA button style.

You'll need to view this as an authenticated user (not a site administrator) to see the form with the frontend theme.

**Comment by jnettik** [comment]
I got the layout styles in place. Didn't get to the button updates.

**Comment by nswitzer** [comment]
Hey @eric-schmidt - Could you add the gray button styles that are used for the register buttons on the registration page to these buttons? Be sure to look at this page as a user that is not an administrator because these styles need to be applied for the form when it's displayed with the frontend theme.

**Comment by eric-schmidt** [comment]
@nswitzer All set!
