### ISSUE TITLE
Redirect anonymous user to sign in/create account page

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#57]
When I'm viewing the site as an anonymous user and click the "Submit Your Session" button, I'm redirected to the 403 page. Can this direct to a page similar to the sign in/create account page commerce uses when an anonymous user is registering for the camp and then redirect back to /node/add/session?

**Comment by jnettik** [comment]
This item is close. Need to figure out why the dev site hates the code that works locally for me.
