### ISSUE TITLE
Theme training product detail pages

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#58]
Trainings are a product type with an accessible detail page. The detail page should be themed to match the news, sponsor and session detail pages.

**Comment by eric-schmidt** [comment]
This is all set and pushed to dev

**Comment by nswitzer** [comment]
Hey @eric-schmidt - Looks good to me! Thanks!

**Comment by nswitzer** [comment]
Hey @eric-schmidt - I'm reopening this issue because it looks like something weird is going on with the date/time field. I'm looking at this training detail: https://full2018.drupalcampcolorado.org.develop.us2.compact.amazee.io/trainings/upgrading-your-local-development-environment-ddev

On the frontend, the node is showing 3:00PM - 9:00PM, but the time entered in the field when you edit the node is 9:00AM - 3:00PM. Could you take a look at this when you have a few minutes?

**Comment by nswitzer** [comment]
Replacing this with text fields seems to be working well. We'll go with it!
