### ISSUE TITLE
Complete project build spec

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#6]
Add all currently known content types, fields, paragraphs and taxonomy vocabularies to the project build spec (link below).

https://docs.google.com/spreadsheets/d/1igEQWAEc-3yj3fbSWZJNRux1kgD0iIoJLV7e7KaUIww/edit?usp=sharing

**Comment by nswitzer** [comment]
Yo @tandroid1 - could you take a look at what I have for the build spec so far? I've added all the components and content types I can see and I've annotated the designs in Invision to show where the components I defined in the build spec show up: https://invis.io/XJE4W9E86#/273515223_Home. The only piece I haven't done yet is the promo that displays two items and appears below the main banner on the homepage - if you have a good idea about how to structure that, feel free to add it in.

**Comment by nswitzer** [comment]
Hey @tandroid1 and @jnettik - I think this is about finished for phase 1. There are still a couple field names we'll need to figure out, but I think that can happen as we build. Could you guys take a look and let me know what kind of feedback you have?

**Comment by jnettik** [comment]
@nswitzer few thoughts:

1. For the distro planning on using the Blog Post label for things I think we're calling news here. To ease alignment would we be fine with using `blog` for the machine name at the very least? We can use a different label if we want to stick with News.
2. I went back and forth on Tags while working on Blog things for the distro. Currently we're planning a "Blog Tags" vocab specific to Blog Posts. In your outline, there's a global Tags vocab using a shared field. Feel like I'm leaning toward your approach, but curious if there's pros/cons to making tags more global.
3. On Sponsors you have `field_image` for the logo, which is a shared image field. If we're using Media would it make more sense to have a field like `field_sponsor_logo` which is an Entity Reference to an image media item?

**Comment by nswitzer** [comment]
@jnettik - 
1. Yep, that's fine with me. I'm fine with changing the human-readable name to Blog as well. Updated in the build spec.
2. I don't have a specific use case for wanting them to be more global, but it would be nice if we ended up with other content we wanted to be able to sort and tag in the same way. If it messes with how the distro will work, I'm good going with a blog-specific vocab.
3. Totally agree here, this was an oversight on my part. I updated field_image in the build spec to be a media reference, so we can have a more generic field to re-use other places around the site. Totally fine with changing how that is named if you think we need something more specific to the field.

**Comment by tmlangley** [comment]
@nswitzer @jnettik - I'm making some edits to the build spec and the biggest thing I wanted to run by you guys is the naming convention for media fields. I prefer to add "media" in the name so it's clear that it's a media field and not a regular file field. For instance, `field_media_image`, `field_media_video` and `field_media_svg`.

**Comment by nswitzer** [comment]
@tandroid1 - Yep, that's a good call. Fine by me.

**Comment by nswitzer** [comment]
@tandroid1 and @jnettik - I think we're set here, so I'm going to go ahead and close this issue.
