### ISSUE TITLE
Theme cart block

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#60]
This doesn't need anything major, but it would be nice to add an orange cart icon to the left of the item count. Something like this maybe: https://thenounproject.com/search/?q=cart&i=1177233

**Comment by eric-schmidt** [comment]
This is all set on dev. Commerce actually had a built in icon, but only black. I went ahead and used that, but changed the link to black as well--I think this matches the utility user menu better anyway. Also, we'll definitely want to remove the News menu item on prod when deploying, as the menu won't fit well with it enabled

**Comment by nswitzer** [comment]
Good find @eric-schmidt! This looks good to me. I'll plan to remove the news item from the main nav when this launches.
