### ISSUE TITLE
Theme empty cart message

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#63]
When the cart is empty, the correct message displays, but it could use some basic layout and margins applied.

https://full2018.drupalcampcolorado.org.develop.us2.compact.amazee.io/cart

**Comment by eric-schmidt** [comment]
@nswitzer This should be good to go on dev--let me know if you think it needs a little more pizzazz...

**Comment by nswitzer** [comment]
@eric-schmidt Looks good to me! Thanks!
