### ISSUE TITLE
Add Training Sponsorship Level

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#64]
We need to add a sponsorship level for trainings that will display the sponsor's logo in a separate category called "Training Sponsor" in the sponsor logos view. The logo should behave like bronze sponsors and click through to the value of the Sponsor Website field on the sponsor node. The training sponsorship type also should not display in the view that lists all sponsorships available for purchase.

**Comment by jnettik** [comment]
@nswitzer this is done and pushed to production. Let me know if you see any tweaks needed.

**Comment by nswitzer** [comment]
Thanks @jnettik!
