### ISSUE TITLE
Build session schedule

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#69]

**Comment by jnettik** [comment]
I've got a start to this on dev: https://full2018.drupalcampcolorado.org.develop.us2.compact.amazee.io/schedule

I'm thinking of something similar to what BadCamp had last year: https://2017.badcamp.net/schedule

The session content type has two new fields for schedule and room. Room is a new taxonomy. I'm not sure if title is enough for that or if we need more fields for more room info. Those two new fields are in a scheduling tab, which only shows up for users with the admin role. That way presenters can edit their session details, but not affect scheduling.

The scheduling view groups things by their day, and then again by their time slots. I'm going to add a jump menu to it that will anchor down to each day in the schedule, probably a little later this week. @nswitzer let me know if anyone could help out with theming this page. I'll be able to work on the jump menu and any other QA in the middle of the week, but this week is going to be pretty broken up for me. I could get to theming next week if there's still stuff needed.

**Comment by nswitzer** [comment]
Thanks for the update @jnettik. @eric-schmidt is going to help out with themeing the session schedule. I've created #70 to track that work.

**Comment by nswitzer** [comment]
Hey @jnettik - Could you also add an 'accepted' boolean to the scheduling tab that is only accessible to site admins and use that to filter sessions that show up on the schedule view?

**Comment by nswitzer** [comment]
Hey @jnettik - Scratch that last thought. I don't think we need an accepted boolean since it looks like sessions aren't added to the schedule until they have a time and room assigned. Let me know if there's anything I'm missing there.

**Comment by jnettik** [comment]
Yeah, the boolean I could go either way on. The view filters out things that have empty schedule fields. But we can add the new field if you still want one. I've finished the anchor menu and that's on dev. I think this is ready to go!

**Comment by jnettik** [comment]
Per our slack conversation, you now have your boolean field! I think this is ready, for real now!

**Comment by nswitzer** [comment]
Thanks @jnettik! This is looking great. Deployed to prod.
