### ISSUE TITLE
Theme Session Schedule

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#70]
The session schedule that @jnettik has been building out needs a little themeing love - you can find it here: https://full2018.drupalcampcolorado.org.develop.us2.compact.amazee.io/schedule

**Comment by eric-schmidt** [comment]
@nswitzer All set and styled on dev 👍

**Comment by nswitzer** [comment]
This is looking great! Thanks @eric-schmidt!
