### ISSUE TITLE
Add and style filter for session track to camp schedule view

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#72]
Camp schedule and content is live on production, but has not been added to the main nav yet. Please add a filter for session track and style to match the feel of the site.

https://2018.drupalcampcolorado.org/schedule

**Comment by eric-schmidt** [comment]
@nswitzer This is done and pushed to dev! I think it could look a bit better, but that would require a bit more of a rewrite of the filtering structure. Let me know if there are any further adjustments you think it could use 👍

**Comment by nswitzer** [comment]
Thanks @eric-schmidt! I appreciate the help on this one.
