### ISSUE TITLE
Style t-shirt product pages

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#73]
These don't need anything too major done because they won't really be public facing, but I'd like them cleaned up a little so they're easier for volunteers to use.

https://2018.drupalcampcolorado.org/product/t-shirt/previous-year
https://2018.drupalcampcolorado.org/product/t-shirt/2018

**Comment by eric-schmidt** [comment]
@nswitzer All set! Went ahead and pushed to prod 👍

**Comment by nswitzer** [comment]
Yes! Thanks @eric-schmidt! This looks great.
