### ISSUE TITLE
Build sponsor content type

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#8]
Content type: Sponsor (machine name: sponsor)
Fields
- Body
- Logo
- Link

**Comment by jnettik** [comment]
@nswitzer There should also be a link field (URL only) for the Sponsor website.

**Comment by jnettik** [comment]
This content type, with a vocabulary for sponsor tiers, and a view to start the display has been pushed. I'm still working on adding the logo and will probably create a draggable view page to let us manually sort within tiers tomorrow.

**Comment by jnettik** [comment]
This content type content type should be ready for theming.

**Comment by nswitzer** [comment]
Sweet, looks good. Thanks @jnettik
