### ISSUE TITLE
Build sponsorship opportunities grid

### ISSUE THREAD

**Issue by nswitzer** [DrupalCampColorado/dcco2018#9]
Design for reference: https://projects.invisionapp.com/share/XJE4W9E86#/screens/272188623

**Comment by jnettik** [comment]
This is finished. There are fields for all the table data (price, availability, features list) on the vocabulary. I was thinking for the "Unlimited" label on some of those levels, we could set the available items to a number below 0 (spots is an integer field) and then override the output either in preprocess or in a Twig template.

**Comment by nswitzer** [comment]
Right on, thanks @jnettik. I think we can plan to handle all of the templating and preprocessing as part of the themeing task.
